---

- name: APT ; install chromium-browser
  become: true
  apt:
    pkg:
      - chromium-browser
    state: present
    update_cache: yes
  register: apt_result
  until: apt_result is not failed
  retries: 30
  delay: 10