---

# - name: APT ; install libssl
#   become: true
#   apt:
#     deb: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/{{ LIBSSL_DEB }}
#   register: apt_result
#   until: apt_result is not failed
#   retries: 2
#   delay: 10

- name: APT_KEY ; add the irods key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.irods.org/irods-signing-key.asc
    state: present
  ignore_errors: true

- name: APT_REPOSITORY | add the irods repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.irods.org/apt/ noble main"
    state: present
  ignore_errors: true

- name: APT ; install irods-icommands
  become: true
  apt:
    name: irods-icommands
    state: present
    update_cache: yes
  register: apt_result
  until: apt_result is not failed
  retries: 2
  delay: 10
  ignore_errors: true

# Might be unnecessary, if this was created by irods install
- name: ensures irods config dir exists
  file: 
    path: "/home/{{ ansible_user }}/.irods/"
    state: directory

- name: COPY ; copy irods anonymous config onto vm
  become: true
  copy:
    src: irods_environment.json
    dest: "/home/{{ ansible_user }}/.irods/irods_environment.json"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
