---

- name: APT ; install jupyter-notebook
  become: true
  apt:
    pkg:
      - jupyter-notebook
    state: present
  register: apt_result
  until: apt_result is not failed
  retries: 2
  delay: 10