---

- name: SET_FACT; set python interpreter
  ansible.builtin.set_fact: ansible_python_interpreter="/usr/bin/python3"

- name: SETUP; gathering facts
  ansible.builtin.setup:
    gather_timeout: 60

- name: INCLUDE_TASKS ; run tasks for primary dev machine setup
  include_tasks: "{{ item }}"
  loop:
    - misc.yaml
    - git_config.yaml
    - ofo-share.yaml
    - irods.yaml
    - ssh_timeout.yaml
    - geograypher.yaml
    - qgis.yaml
    - r.yaml
    - anaconda.yaml
    - metashape.yaml
    - sublime.yaml
    - jupyter.yaml
    - rstudio_ssl.yaml
  when: RUN_MAIN==true

- name: INCLUDE_TASKS ; run tasks for private folder setup
  include_tasks: "{{ item }}"
  loop:
    - private_folder.yaml
  when: RUN_PRIVATE==true
