---

- name: SET_FACT; set python interpreter
  ansible.builtin.set_fact: ansible_python_interpreter="/usr/bin/python3"

- name: SETUP; gathering facts
  ansible.builtin.setup:
    gather_timeout: 60

- name: INCLUDE_TASKS ; run tasks for primary dev machine setup
  include_tasks: "{{ item }}"
  loop:
    - ssh_timeout.yaml
    - misc.yaml
    - r.yaml
    - ofo-share.yaml
    - irods.yaml
    - geograypher.yaml
    - qgis.yaml
    - anaconda.yaml
    - metashape.yaml
    - sublime.yaml
    - jupyter.yaml
    - rstudio_ssl.yaml
  when: RUN_MAIN == 'yes'

- name: INCLUDE_TASKS ; run tasks for private folder setup
  include_tasks: "{{ item }}"
  loop:
    - setup_private_folder.yaml
  when: RUN_PRIVATE == 'yes'

- name: APT ; update and upgrade system packages
  become: true
  apt:
    upgrade: dist
    update_cache: yes
  register: apt_result
  until: apt_result is not failed
  retries: 2
  delay: 10
