---

- name: SET_FACT; set python interpreter
  ansible.builtin.set_fact: ansible_python_interpreter="/usr/bin/python3"

- name: SETUP; gathering facts
  ansible.builtin.setup:
    gather_timeout: 60

- include_tasks: misc.yaml
- include_tasks: git_config.yaml
- include_tasks: ofo-share.yaml
- include_tasks: irods.yaml
- include_tasks: ssh_timeout.yaml
- include_tasks: geograypher.yaml
- include_tasks: qgis.yaml
- include_tasks: r.yaml
- include_tasks: anaconda.yaml
- include_tasks: metashape.yaml
- include_tasks: sublime.yaml
- include_tasks: jupyter.yaml
- include_tasks: rstudio_ssl.yaml
