- name: LINEINFILE ; ensure alias ls='ls --color=auto' in .bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "alias ls='ls --color=auto'"

- name: LINEINFILE ; set up GPG as needed for YADM (https://mroldan.medium.com/gpg-symmetric-encryption-of-stdin-failed-operation-cancelled-f6c1bd90be9d)
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: 'export GPG_TTY=$(tty)'

- name: APT ; install rclone and ansible and all other misc packages
  become: true
  apt:
    pkg:
      - rclone
      - ansible-core
      - wget
      - ca-certificates
      - yadm
      - libimage-exiftool-perl
    state: present
    update_cache: yes
  register: apt_result
  until: apt_result is not failed
  retries: 2
  delay: 10

- name: COPY ; copy setup-private-folder.sh script
  become: true
  copy:
    src: setup-private-folder.sh
    dest: /opt/setup-private-folder.sh
    mode: 0744
    owner: "{{ ansible_user }}"

# Implementing this suggestion from JS2 support: Try editing
# /etc/nvidia-container-runtime/config.toml ; uncomment the user = "root:video" line, and change it
# to user = "root:root"
- name: Fix NVIDIA container runtime config
  become: true
  ini_file:
    path: /etc/nvidia-container-runtime/config.toml
    section: nvidia-container-cli
    option: user
    value: '"root:root"'
    state: present

- name: SHELL ; install untwine in new conda env
  shell:
    cmd: "~/miniconda3/bin/conda create -n untwine -y -c conda-forge untwine"
    creates: /home/{{ ansible_user_id }}/miniconda3/envs/untwine/bin/untwine
  args:
    executable: /bin/bash
