# Set up a private folder for user to store credentials, move credentials files to this folder, and
# create symlinks pointing to this folder

- name: APT ; install ecryptfs-utils
  become: true
  apt:
    pkg:
      - ecryptfs-utils
    state: present
    update_cache: yes
  register: apt_result
  until: apt_result is not failed
  retries: 2
  delay: 10
  
- name: SHELL ; run 'ecryptfs-setup-private'
  shell:
    cmd: ecryptfs-setup-private --noautomount -u {{ ansible_user }} -l '{{ CREDS_PASSWORD }}' -m '{{ CREDS_PASSWORD }}'
  args:
    executable: /bin/bash
    creates: ~/Private
    
- name: EXPECT ; mount the private folder by providing the password at the prompt
  expect:
    command: ecryptfs-mount-private
    responses:
      (?i)Enter your login passphrase:
        - "{{ CREDS_PASSWORD }}"

- name: FILE; create the folders for the config files if they don't exist
  file:
    path: ~/.config/rclone/
    state: directory

- name: COPY ; put blank config files in the private folder if they don't exist
  copy:
    content: ""
    dest: "{{ item }}"
    force: false
  with_items:
    - "~/Private/.git-credentials"
          
- name: Create symlink for .git-credentials that points to the private folder
  ansible.builtin.file:
    path: ~/.git-credentials
    src: ~/Private/.git-credentials
    state: link
