---

- name: GET_URL | get the apt key
  ansible.builtin.get_url:
    url: https://download.qgis.org/downloads/qgis-archive-keyring.gpg
    dest: /etc/apt/keyrings/qgis-archive-keyring.gpg 
  become: true

# - name: COPY ; copy /etc/apt/sources.list.d/qgis.sources
#   become: true
#   copy:
#     src: qgis.sources_{{ ansible_distribution_release }}
#     dest: /etc/apt/sources.list.d/qgis.sources
    
- name: TEMPLATE ; template the qgis.sources file
  become: true
  template:
    src: "qgis.sources.j2"
    dest: "/etc/apt/sources.list.d/qgis.sources"

- name: APT ; install qgis
  become: true
  apt:
    pkg:
      - qgis 
      - qgis-plugin-grass
    state: present
    update_cache: yes
  register: apt_result
  until: apt_result is not failed
  retries: 2
  delay: 10