---

- name: LINEINFILE ; configure sshd
  become: true
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{keyval.key}}"
    line: "{{keyval.key}} {{keyval.value}}"
    state: present
  loop:
    - { key: "ClientAliveInterval", value: "300" }
    - { key: "ClientAliveCountMax", value: "36" }
  loop_control:
    loop_var: keyval

- name: restart sshd
  service:
    name: sshd.service
    state: restarted
  become: true
